# This is used to uniquely label the services according to the node they are running on
EnableGPS: true

# These are related to the rbac.yaml permissions file. The user may want to install their own
# service account and bindings, etc. The service account is named here, and the InstallRbac
# specifies if the user wants this helm package to install the accounts and rights. These
# may already be installed by the user
ServiceAccount: silicom
InstallRbac: false

Images:
  Tsyncd: quay.io/silicom/tsyncd:2.1.2.7
  TsyncExtts: quay.io/silicom/tsync_extts:1.0.0
  Phc2Sys: quay.io/silicom/phc2sys:3.1.1
  GrpcTsyncd: quay.io/silicom/grpc-tsyncd:2.1.2.7
  Gpsd: quay.io/silicom/gpsd:3.23.1
GrpcSvcPort: 50051
GrpcEvntPort: 50052
GrpcCfgPort: 50053
GrpcStatPort: 50054
GrpcTimingMgr: 50055

GpsSvcPort: 2947

Spec:
  profileID: 2
  ports:
  - ethName: enp101s0f0
    ql: 4
    portSpeed: 10000
    ethPort: 1
  - ethName: enp101s0f1
    ql: 4
    portSpeed: 10000
    ethPort: 2
  - ethName: enp101s0f2
    ql: 4
    portSpeed: 10000
    ethPort: 3
  - ethName: enp101s0f3
    ql: 4
    portSpeed: 10000
    ethPort: 4
  - ethName: enp101s0f4
    ql: 4
    portSpeed: 10000
    ethPort: 5
  - ethName: enp101s0f5
    ql: 4
    portSpeed: 10000
    ethPort: 6
  - ethName: enp101s0f6
    ql: 4
    portSpeed: 10000
    ethPort: 7
  - ethName: enp101s0f7
    ql: 4
    portSpeed: 10000
    ethPort: 8
  - ethName: enp103s0f0
    ql: 4
    portSpeed: 25000
    ethPort: 9
  - ethName: enp103s0f1
    ql: 4
    portSpeed: 25000
    ethPort: 10
  - ethName: enp103s0f2
    ql: 4
    portSpeed: 25000
    ethPort: 11
  - ethName: enp103s0f3
    ql: 4
    portSpeed: 25000
    ethPort: 12    
  masterPortMask_GM: 0xfff
  masterPortMask_BC: 0xfff
  slavePortMask_BC: 0xfff
  slavePortMask_TSC: 0xfff
  ipv6PortMask: 0x000
  domainNum_8275_1: 24
  domainNum_8275_2: 44
  domainNum_8265_2: 4
  forwardable: 1
  twoStep: 0
  freerunSQ: 0
  priority2: 128
  modePPS: 2
  mode10MHz: 2
  srcPPS: 1
  src10MHz: 1
  freqCat: 3
  hoSpecDuration: 14400
  synceRecClkMode: 2
  synceRecClkPort: 0
  syncOption: 1
  esmcMode: 2
  ssmMode: 1
  syncePortMask_GM: 0xfff
  syncePortMask_BC: 0xfff
  syncePortMask_TSC: 0xfff
  synceHoldOff: 500
  gpsdDbgLevel: 2 
  gnssSigGpsEn: 1
  gnssSigGpsL1CAEn: 1
  gnssSigGpsL2CEn: 1
  gnssSigSBASEn: 1
  gnssSigSBASL1CAEn: 0
  gnssSigGalEn: 1
  gnssSigGalE1En: 1
  gnssSigGalE5BEn: 1
  gnssSigBDSEn: 1
  gnssSigBDSB1En: 1
  gnssSigBDSB2En: 1
  gnssSigQZSSEn: 1
  gnssSigQZSSL1CAEn: 1
  gnssSigQZSSL1SEn: 0
  gnssSigQZSSL2CEn: 1
  gnssSigGLOEn: 1
  gnssSigGLOL1En: 1
  gnssSigGLOL2En: 1
  gnssCableDelay: 50
  gnssPulseDef: 1
  gnssPulseLenDef: 0
  gnssFreqTP1: 1
  gnssFreqLockTP1: 1
  gnssUseLockTP1: 1
  gnssDutyTP1: 0
  gnssDutyLockTP1: 10
  gnssFreqTP2: 10000000
  gnssFreqLockTP2: 10000000
  gnssUseLockTP2: 1
  gnssDutyTP2: 0
  gnssDutyLockTP2: 50
  gnssMinElev: 5
  gnssMinSatSig: 9
  gnssMsgNmeaUsb: 7
  gnssMsgUbxUsb: 0
  gnssIntfDetect: 1
  gnssAntSet: 2
  gnssCwTh: 50
  gnssRecvTMode: 1
  gnssSvinMinDur: 120
  gnssSvinAccLimit: 100000
  gnssLockMode: 1
  gnssLockTh: 100
  gnssClockOutEn: 0
  stsCpu: 10
  phaseOfstEn_GM: 0
  phaseOfstVal_GM: 1948960
  IPCServer: 1
  swTimestamp: 0
  inbandMode: 1 
  dumpMode: 0
  getRawTs: 0
  aprLevel: 0
  traceModule: 23
  traceLevel: 0
  tracePtpMsg: -1
  whenWriteLog: 0
  taccLogEn: 0
  phyLedsCtl: 0
  eventMask: 3
  gnssTP1En: 0
  gnssTP2En: 0
  debugAPI: 0
