apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "node.tsync.name" . }}
  namespace: {{.Release.Namespace}}
  labels:
    app: grpc_tsyncd    
spec:
  selector:
    matchLabels:
      app: grpc_tsyncd      
  template:
    metadata:
      labels:
        app: grpc_tsyncd        
    spec:
      shareProcessNamespace: true
      nodeSelector:
{{- range $k, $v := .Values.NodeSelectors }}
        {{ $k }}: "{{ $v }}"
{{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - image: {{.Values.Images.Gpsd}}
        imagePullPolicy: Always
        name: {{ template "node.gps.name" . }}
        ports:
        - containerPort: {{.Values.GpsSvcPort}}
          name: {{ template "node.gps.name" . }}
        env:
        - name: GPS_SVC_PORT
          value: {{.Values.GpsSvcPort | quote}}
        - name: STS_Cpu
          value: {{.Values.Spec.stsCpu | quote}}
        volumeMounts:
        - name: devfs
          mountPath: /dev
        securityContext:
          privileged: true

      - image: {{ .Values.Images.GrpcTsyncd }}
        imagePullPolicy: Always
        name: {{template "node.grpc.name" . }}
        ports:
        - containerPort: {{.Values.GrpcSvcPort}}
          name: {{template "node.grpc.name" . }}
        - containerPort: {{.Values.GrpcEvntPort}}        
          name: {{template "node.grpcevnt.name" . }}
        - containerPort: {{.Values.GrpcCfgPort}}
          name: {{template "node.grpccfg.name" . }}
        - containerPort: {{.Values.GrpcStatPort}}
          name: {{template "node.grpcstat.name" . }}
        - containerPort: {{.Values.GrpcTimingMgr}}
          name: {{template "node.grpctimingmgr.name" . }}
        env:
        - name: STS_Cpu
          value: {{.Values.Spec.stsCpu | quote}}
        volumeMounts:
          - name: logs
            mountPath: /var/log
          - name: {{printf "%.*s-cfg" 11 .Release.Name | quote}}
            mountPath: /etc/tsyncd/tsyncd_grpc.json
            subPath: tsyncd_grpc.json            
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          capabilities:
            add:
            - CAP_SYS_ADMIN
            
      - image: {{.Values.Images.Tsyncd}}
        imagePullPolicy: Always
        name: {{ template "node.tsync.name" . }}
        env:
        - name: WAIT_FOR_GPS
          value: {{.Values.EnableGPS | quote}}
        - name: GPS_SVC_PORT
          value: "{{.Values.GpsSvcPort}}"
        - name: STS_Cpu
          value: {{.Values.Spec.stsCpu | quote}}
{{- if or (eq (.Values.Spec.profileID | int) 1) (eq (.Values.Spec.profileID | int) 2) (eq (.Values.Spec.profileID | int) 5) }}
        - name: GM_MODE
          value: "-g"
{{- end}}          
        args:
        - --zap-log-level=10
        volumeMounts:
          - name: devfs
            mountPath: /dev
          - name: {{printf "%.*s-cfg" 11 .Release.Name | quote}}
            mountPath: /etc/tsyncd/tsyncd.conf
            subPath: tsyncd.conf
          - name: logs
            mountPath: /var/log
        securityContext:
          privileged: true

      - image: {{.Values.Images.Phc2Sys}}
        name: {{ template "node.phc2sys.name" . }}
        imagePullPolicy: Always
        env:
        - name: WAIT_FOR_GPS
          value: {{.Values.EnableGPS | quote}}
        - name: GPS_SVC_PORT
          value: {{.Values.GpsSvcPort | quote}}
        - name: STS_Cpu
          value: {{.Values.Spec.stsCpu | quote}}          
        volumeMounts:
        - name: devfs
          mountPath: /dev
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
          capabilities:
            add:
            - CAP_SYS_TIME
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: {{printf "%.*s-cfg" 11 .Release.Name | quote}}
        configMap:
          defaultMode: 0777
          name: {{printf "%.*s-cfg" 11 .Release.Name | quote}}
      - name: logs
        emptyDir: {}
